---
title: "Intro to sf package for Spatial Data and Making Maps"
author: "Ted Flynn"
date: "2023-04-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load Packages
```{r load packages, warning=FALSE, message=FALSE}
library(readr)
library(sf)
library(ggplot2)
library(leaflet)
library(scales)
library(ggmap) # add base map to static map
library(dplyr)
```

### Read in Shape Data
```{r read in data}
# read in shapefile using read_sf()
ak_regions <- read_sf("data/ak_regions_simp.shp")
```

### Quick Plot
```{r quick plot, warning=FALSE, message=FALSE, echo=FALSE}
# quick plot
plot(ak_regions)
```

### Preview data frame
```{r preview data, warning=FALSE, message=FALSE, echo=FALSE}
head(ak_regions)

glimpse(ak_regions)
```
### Transform Coordinate System
```{r transform data coordinates}

# Alaska Albers correction is the most common for this region
# More here: https://spatialreference.org/ref/epsg/?page=1
ak_regions_3338 <- ak_regions %>%
    st_transform(crs = 3338)

```

### Plot Transformed Data
```{r plot transformed}
plot(ak_regions_3338)
```

### sf and the Tidyverse
```{r view colnames}
colnames(ak_regions_3338)
```

```{r select region}
ak_regions_3338 %>% select(region)
```

```{r filter Yukon, warning=FALSE, message=FALSE}
ak_regions_3338 %>% filter(region == "Yukon")
```

### Spatial Joins

```{r spatial joins}
pop <- read_csv("data/alaska_population.csv")


```

```{r create sf object from pop}
pop_4326 <- st_as_sf(pop, 
                     coords = c("lng","lat"),
                     crs = 4326,
                     remove = FALSE)

head(pop_4326)
```

```{r join pop data}
# Will throw an error because we need to convert our CRS data
# pop_joined <- st_join(pop_4326, 
#                       ak_regions_3338, 
#                       join = st_within)
```

```{r convert to crs 3338}
pop_3338 <- st_transform(pop_4326, crs = 3338)
```

```{r join regions with pop}
pop_joined <- st_join(pop_3338, ak_regions_3338, join = st_within)
```

```{r calc total pop}
pop_region <- pop_joined %>%
    as.data.frame() %>%
    group_by(region) %>%
    summarise(total_pop = sum(population))

head(pop_region)

class(pop_region) # Need to convert to be an sf object
```

```{r join pop and regions_3338}
pop_region_3338 <- left_join(ak_regions_3338, pop_region, by = "region")

class(pop_region_3338)
```

```{r}
plot(pop_region_3338["total_pop"])
```

```{r}
pop_mgmt_338 <- pop_region_3338 %>%
    group_by(mgmt_area) %>%
    summarize(total_pop = sum(total_pop))

plot(pop_mgmt_338["total_pop"])
```

```{r}
pop_mgmt_3338 <- pop_region_3338 %>%
    group_by(mgmt_area) %>%
    summarize(total_pop = sum(total_pop), do_union = FALSE)

plot(pop_mgmt_3338["total_pop"])
```

```{r}
write_sf(pop_region_3338, "data/ak_regions_population.shp")
```

### Visualize with ggplot

```{r}
ggplot(pop_region_3338) +
    geom_sf(aes(fill = total_pop)) +
    labs(fill = "Total Population") +
    scale_fill_continuous(low = "khaki",
                          high =  "firebrick",
                          labels = comma) +
    theme_bw()
```

### Add rivers spatial data
```{r}
rivers_3338 <- read_sf("data/ak_rivers_simp.shp")
st_crs(rivers_3338)
```

```{r}
ggplot() +
  geom_sf(data = pop_region_3338, aes(fill = log10(total_pop))) +
  geom_sf(pop_3338, mapping = aes()) +
  geom_sf(data = rivers_3338, aes(linewidth = StrOrder)) +
  scale_linewidth(range = c(0.05, 0.5), guide = "none") +
  labs(title = "Total Population by Alaska Region",
       fill = "Total Population") +
  scale_fill_continuous(type = "viridis", labels = comma) +
  theme_bw()
```

### Making leaflet maps

```{r leaflet}
epsg3338 <- leaflet::leafletCRS(
  crsClass = "L.Proj.CRS",
  code = "EPSG:3338",
  proj4def =  "+proj=aea +lat_1=55 +lat_2=65 +lat_0=50 +lon_0=-154 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs",
  resolutions = 2 ^ (16:7)
)
```

```{r}
st_crs(pop_region_3338)

pop_region_4326 <- pop_region_3338 %>% st_transform(crs = 4326)
```

```{r}
m <- leaflet(options = leafletOptions(crs = epsg3338)) %>%
    addPolygons(data = pop_region_4326,
                fillColor = "gray",
                weight = 1)

m
```

