---
title: 'R Practice: Spatial Data and Making Maps'
author: "Ted Flynn"
date: "2023-04-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages
```{r load, warning=FALSE, message=FALSE}
library(readr)
library(dplyr)
library(sf)
library(ggplot2)
library(scales)
library(leaflet)
library(ggmap)
```

## Read in Raw Data
```{r read in data, warning=FALSE, message=FALSE}
pika <- read_csv("data/pika_fecal_glut.aw.data.csv")
elevation <- read_csv("data/pika_fecal_glut_habitat.aw.data.csv")
```

## Evaluate the Data
```{r evaluate data, warning=FALSE, message=FALSE, eval=FALSE}
glimpse(pika)

head(pika)

range(pika$Date) # Dates from Jun - Sept 2018

table(pika$Station) 

unique(pika$Site) # 3 unique sites

is.na(pika$Concentration_pg_g) # no NAs

```

## Wrangle Data
```{r wrangle data}
pika_clean <- pika %>% 
  select(Date:UTM_Northing,Concentration_pg_g,Site,Sex)

# Replace 
pika_clean <- pika_clean %>% 
  relocate(Station, .before = Site) %>%
  relocate(Sex, .after = UTM_Northing) %>% 
  mutate(across(Station:Sex, ~ as.factor(.x)))

# Replace site abbreviations
pika_clean <- pika_clean %>% 
  mutate(Site = case_match(Site,
             "CG" ~ "Cable Gate",
             "WK" ~ "West Knoll",
             "LL" ~ "Long Lake"))

elevation_clean <- elevation %>% 
  select(Station, Elev_M) %>%
  mutate(Station = as.factor(Station))


```

## Merge Data
```{r merge}
pikas <- full_join(pika_clean, elevation_clean, by = "Station")

```

## Convert to Simple Features
```{r convert to sf}
pikas_sf <- st_as_sf(pikas,
                     coords = c("UTM_Easting","UTM_Northing")) 

class(pikas_sf)

pikas_sf <- st_set_crs(pikas_sf, value = 26913)

st_crs(pikas_sf)
```

## Plot using `ggplot()`
```{r plot with ggplot}
m_pikas <- ggplot(data = pikas_sf) +
  geom_sf(aes(color = Site,
              shape = Site)) +
  labs(x = "Longitude",
       y = "Latitude",
       title = "Stress in Pikas") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 30,
                                    vjust = 0.5))
  

m_pikas
```

## Transform Coordinates Again
```{r transform 4326}
pikas_sf_4326 <- st_transform(pikas_sf, crs = 4326)

st_crs(pikas_sf_4326)
```

## Set Bounding Box
```{r bbox}
nwt_bbox <- c(left = -105.65, bottom = 40.04, right = -105.55, top = 40.1)

class(nwt_bbox)
```

## 
```{r add basemap}
nwt_basemap <- ggmap::get_stamenmap(nwt_bbox, zoom = 13, 
                                    maptype = "terrain")

ggmap(nwt_basemap)
```

## Plot Finished Map
```{r}
m_pikas_base <- ggmap(nwt_basemap) +
  geom_sf(data = pikas_sf_4326,
          mapping = aes(fill = Site, size = 1),
          pch = 21,
          color = "black",
          inherit.aes = FALSE) +
  labs(x = "Longitude",
       y = "Latitude",
       title = "Stress in Pikas") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 30,
                                   vjust = 0.5))


m_pikas_base
```

